from tkinter import*
root=Tk()
root.geometry("600x600")
root.title("Calculator")
# root.wm_iconbitmap("1co.ico")
mainframe=Frame(root,relief=RIDGE,bg="black",bd=10)
mainframe.pack()
def click(event):
    global calvar
    text=event.widget.cget("text")
    if text=="C":
        calvar.set("")
        e.update()
    elif text=="=":
        if calvar.get().isdigit():
            value=int(calvar.get())
        else:
            try:
                value=eval(calvar.get())
            except Exception as e1:
                value="Error"
        calvar.set(value)
        e.update()
    else:
        calvar.set(calvar.get()+text)
        e.update()
calvar=StringVar()
calvar.set("")
e=Entry(mainframe,bg="white",font="lucida 18 bold",width=35,textvariable=calvar)
e.grid(row=0,column=0,columnspan=4)

b=Button(mainframe,text="1",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=1,column=0)
b.bind("<Button-1>",click)
b=Button(mainframe,text="2",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=1,column=1)
b.bind("<Button-1>",click)
b=Button(mainframe,text="3",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=1,column=2)
b.bind("<Button-1>",click)
b=Button(mainframe,text="C",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=1,column=3)
b.bind("<Button-1>",click)
b=Button(mainframe,text="4",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=2,column=0)
b.bind("<Button-1>",click)
b=Button(mainframe,text="5",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=2,column=1)
b.bind("<Button-1>",click)
b=Button(mainframe,text="6",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=2,column=2)
b.bind("<Button-1>",click)
b=Button(mainframe,text="+",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=2,column=3)
b.bind("<Button-1>",click)
b=Button(mainframe,text="7",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=3,column=0)
b.bind("<Button-1>",click)
b=Button(mainframe,text="8",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=3,column=1)
b.bind("<Button-1>",click)
b=Button(mainframe,text="9",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=3,column=2)
b.bind("<Button-1>",click)
b=Button(mainframe,text="-",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=3,column=3)
b.bind("<Button-1>",click)
b=Button(mainframe,text="0",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=4,column=0)
b.bind("<Button-1>",click)
b=Button(mainframe,text="=",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=4,column=1)
b.bind("<Button-1>",click)
b=Button(mainframe,text="*",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=4,column=2)
b.bind("<Button-1>",click)
b=Button(mainframe,text="/",bg="#777B7E",width=5,relief=RIDGE,padx=30,pady=10,font="5")
b.grid(row=4,column=3)
b.bind("<Button-1>",click)
root.mainloop()